name: Build and Push Docker Image
# Push Event: The workflow will run whenever there is a push to the main branch. 
# This means that any time code is committed and pushed to the main branch, the workflow will be executed. 
# This is useful for ensuring that any changes made to the main branch are automatically tested or deployed.
# Pull Request Event: The workflow will also run when a pull request is opened, synchronized, or reopened, 
# but only if the pull request targets the main branch. 
# This helps in validating the changes proposed in the pull request before they are merged into the main branch, 
# ensuring that the code meets the required standards and passes all tests.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run tests with Maven
      id: test
      run: mvn clean verify
      
    # - name: Run tests and check coverage
    #   run: mvn test jacoco:report jacoco:check
            
    - name: Set up Docker Buildx
    # This configuration ensures that the Docker image is only built and pushed when the event is a push to the main branch, not when a pull request is opened.
      if: github.event_name == 'push'
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Git
      if: github.event_name == 'push'
      run: git fetch --tags

    - name: Get the latest Git tag
      if: github.event_name == 'push'
      id: git_tag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

    - name: Build and Push Docker Image
      if: github.event_name == 'push' && steps.test.outcome == 'success' && steps.git_tag.outputs.tag != ''
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/accessing-data-rest:${{ steps.git_tag.outputs.tag }}

    - name: Verify Image at Docker Hub
      if: github.event_name == 'push' && steps.test.outcome == 'success' && steps.git_tag.outputs.tag != ''
      run: |
        echo "Docker Image pushed successfully to Docker Hub."
